/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author User
 */
public class HomePegawai extends javax.swing.JFrame {

    /**
     * Creates new form HomePegawai
     */
    public HomePegawai() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        homeButton = new javax.swing.JButton();
        obatButton = new javax.swing.JButton();
        pelangganButton = new javax.swing.JButton();
        penjualanButton = new javax.swing.JButton();
        pembelianButton = new javax.swing.JButton();
        laporanButton1 = new javax.swing.JButton();
        laporanButton2 = new javax.swing.JButton();
        buttonLaporanPembelian = new javax.swing.JButton();
        buttonLaporanPenjualan = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeMenu = new javax.swing.JMenu();
        masterMenu = new javax.swing.JMenu();
        dataObat = new javax.swing.JMenuItem();
        dataPelanggan = new javax.swing.JMenuItem();
        transaksiMenu = new javax.swing.JMenu();
        penjualan = new javax.swing.JMenuItem();
        pembelian = new javax.swing.JMenuItem();
        laporanMenu = new javax.swing.JMenu();
        laporan1 = new javax.swing.JMenuItem();
        laporanObat = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon home.png"))); // NOI18N
        homeButton.setToolTipText("Home");
        homeButton.setFocusable(false);
        homeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        homeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(homeButton);

        obatButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon obat.png"))); // NOI18N
        obatButton.setToolTipText("Form Data Obat");
        obatButton.setFocusable(false);
        obatButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        obatButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        obatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obatButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(obatButton);

        pelangganButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon pelanggan.png"))); // NOI18N
        pelangganButton.setToolTipText("Form Data Pelanggan");
        pelangganButton.setFocusable(false);
        pelangganButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pelangganButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pelangganButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelangganButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(pelangganButton);

        penjualanButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon penjualan.png"))); // NOI18N
        penjualanButton.setToolTipText("Transaksi Penjualan");
        penjualanButton.setFocusable(false);
        penjualanButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        penjualanButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        penjualanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(penjualanButton);

        pembelianButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon pembelian.png"))); // NOI18N
        pembelianButton.setToolTipText("Transaksi Pembelian");
        pembelianButton.setFocusable(false);
        pembelianButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pembelianButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pembelianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembelianButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(pembelianButton);

        laporanButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon data pelanggan.png"))); // NOI18N
        laporanButton1.setToolTipText("Laporan Data Pelanggan");
        laporanButton1.setFocusable(false);
        laporanButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        laporanButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        laporanButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(laporanButton1);

        laporanButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon laporan.png"))); // NOI18N
        laporanButton2.setToolTipText("Laporan Data Obat");
        laporanButton2.setFocusable(false);
        laporanButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        laporanButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        laporanButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(laporanButton2);

        buttonLaporanPembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon laporan pembelian.png"))); // NOI18N
        buttonLaporanPembelian.setToolTipText("Laporan Transaksi Pembelian");
        buttonLaporanPembelian.setFocusable(false);
        buttonLaporanPembelian.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonLaporanPembelian.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonLaporanPembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLaporanPembelianActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonLaporanPembelian);

        buttonLaporanPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon laporan penjualan.png"))); // NOI18N
        buttonLaporanPenjualan.setToolTipText("Laporan Transaksi Penjualan");
        buttonLaporanPenjualan.setFocusable(false);
        buttonLaporanPenjualan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonLaporanPenjualan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buttonLaporanPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLaporanPenjualanActionPerformed(evt);
            }
        });
        jToolBar1.add(buttonLaporanPenjualan);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon help.png"))); // NOI18N
        jButton1.setToolTipText("Help");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton1);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/1485969675-18-information_78897 (1).png"))); // NOI18N
        jButton2.setToolTipText("About");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/perawat.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon apotik.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BINUS FARMA");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SELAMAT DATANG DI APOTEK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel2)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)))
                .addGap(29, 29, 29)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        homeMenu.setText("Home");
        homeMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuBar1.add(homeMenu);

        masterMenu.setText("Master");
        masterMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        dataObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon obat.png"))); // NOI18N
        dataObat.setText("Data Obat");
        dataObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataObatActionPerformed(evt);
            }
        });
        masterMenu.add(dataObat);

        dataPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon pelanggan.png"))); // NOI18N
        dataPelanggan.setText("Data Pelanggan");
        dataPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataPelangganActionPerformed(evt);
            }
        });
        masterMenu.add(dataPelanggan);

        jMenuBar1.add(masterMenu);

        transaksiMenu.setText("Transaksi");
        transaksiMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        penjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon penjualan.png"))); // NOI18N
        penjualan.setText("Penjualan");
        penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penjualanActionPerformed(evt);
            }
        });
        transaksiMenu.add(penjualan);

        pembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon pembelian.png"))); // NOI18N
        pembelian.setText("Pembelian");
        pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembelianActionPerformed(evt);
            }
        });
        transaksiMenu.add(pembelian);

        jMenuBar1.add(transaksiMenu);

        laporanMenu.setText("Laporan");
        laporanMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        laporan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon data pelanggan.png"))); // NOI18N
        laporan1.setText("Laporan Pelanggan");
        laporan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporan1ActionPerformed(evt);
            }
        });
        laporanMenu.add(laporan1);

        laporanObat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon laporan.png"))); // NOI18N
        laporanObat.setText("Laporan Data Obat");
        laporanObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanObatActionPerformed(evt);
            }
        });
        laporanMenu.add(laporanObat);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon data transaksi.png"))); // NOI18N
        jMenu1.setText("Laporan Transaksi");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon laporan pembelian.png"))); // NOI18N
        jMenuItem1.setText("Laporan Pembelian");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon laporan penjualan.png"))); // NOI18N
        jMenuItem2.setText("Laporan Penjualan");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        laporanMenu.add(jMenu1);

        jMenuBar1.add(laporanMenu);

        helpMenu.setText("Help");
        helpMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItem4.setText("Hubungi Kami");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        helpMenu.add(jMenuItem4);

        jMenuBar1.add(helpMenu);

        jMenu3.setText("About");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Info Aplikasi");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataObatActionPerformed
    new FormDataObat().setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_dataObatActionPerformed

    private void dataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataPelangganActionPerformed
    new FormPelanggan().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_dataPelangganActionPerformed

    private void obatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obatButtonActionPerformed
    new FormDataObat().setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_obatButtonActionPerformed

    private void pelangganButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelangganButtonActionPerformed
    new FormPelanggan().setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_pelangganButtonActionPerformed

    private void penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanActionPerformed
    new Penjualan().setVisible(true);
    }//GEN-LAST:event_penjualanActionPerformed

    private void pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembelianActionPerformed
    new Pembelian().setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_pembelianActionPerformed

    private void laporan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporan1ActionPerformed
    new LaporanPelanggan().setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_laporan1ActionPerformed

    private void laporanObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanObatActionPerformed
    new LaporanBarang().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_laporanObatActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    new LaporanPembelian().setVisible(true);  
    this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
    new LaporanPenjualan().setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void penjualanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penjualanButtonActionPerformed
    new Penjualan().setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_penjualanButtonActionPerformed

    private void pembelianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembelianButtonActionPerformed
    new Pembelian().setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_pembelianButtonActionPerformed

    private void laporanButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanButton1ActionPerformed
    new LaporanPelanggan().setVisible(true);  
    this.dispose();
    }//GEN-LAST:event_laporanButton1ActionPerformed

    private void laporanButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanButton2ActionPerformed
    new LaporanBarang().setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_laporanButton2ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        new FormHelp().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        new FormAbout().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void buttonLaporanPembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLaporanPembelianActionPerformed
        // TODO add your handling code here:
        new LaporanPembelian().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonLaporanPembelianActionPerformed

    private void buttonLaporanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLaporanPenjualanActionPerformed
        // TODO add your handling code here:
        new LaporanPenjualan().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonLaporanPenjualanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomePegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomePegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomePegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomePegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomePegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLaporanPembelian;
    private javax.swing.JButton buttonLaporanPenjualan;
    private javax.swing.JMenuItem dataObat;
    private javax.swing.JMenuItem dataPelanggan;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JButton homeButton;
    private javax.swing.JMenu homeMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem laporan1;
    private javax.swing.JButton laporanButton1;
    private javax.swing.JButton laporanButton2;
    private javax.swing.JMenu laporanMenu;
    private javax.swing.JMenuItem laporanObat;
    private javax.swing.JMenu masterMenu;
    private javax.swing.JButton obatButton;
    private javax.swing.JButton pelangganButton;
    private javax.swing.JMenuItem pembelian;
    private javax.swing.JButton pembelianButton;
    private javax.swing.JMenuItem penjualan;
    private javax.swing.JButton penjualanButton;
    private javax.swing.JMenu transaksiMenu;
    // End of variables declaration//GEN-END:variables
}
